//bookings
export const GET_BOOKINGS_DATA_REQUEST = 'GET_BOOKINGS_DATA_REQUEST';
export const GET_BOOKINGS_DATA_SUCCESS = 'GET_BOOKINGS_DATA_SUCCESS';
export const GET_BOOKINGS_DATA_FAILURE = 'GET_BOOKINGS_DATA_FAILURE';

//rooms
export const GET_ROOMS_DATA_REQUEST ='GET_ROOMS_DATA_REQUEST';
export const GET_ROOMS_DATA_SUCCESS ='GET_ROOMS_DATA_SUCCESS';
export const GET_ROOMS_DATA_FAILURE ='GET_ROOMS_DATA_FAILURE';
